### ISSUE TITLE
Outdated es.json

### ISSUE THREAD

**Issue by coderdiaz** [coderdiaz/vue-cli-locale-es#4]
## Need
- Update the `es.json` file to new specs.

Ref.
https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/cli-ui/locales/en.json

**Comment by jatempa** [comment]
I want to work on this !

**Comment by coderdiaz** [comment]
@jatempa Awesome!

**Comment by caugner** [comment]
@coderdiaz Note that it looks like the Spanish locale is already `ready for use` [on Transifex](https://www.transifex.com/vuejs/vue-cli/language/es/).

The JSON file can be exported here (click on `cli-ui` and choose `Download for use`):
https://www.transifex.com/vuejs/vue-cli/language/es/

**Comment by coderdiaz** [comment]
@caugner Cool! Thanks man!

**Comment by caugner** [comment]
@coderdiaz Short update, there are actually 54 untranslated keys: https://www.transifex.com/vuejs/vue-cli/translate/#es/cli-ui/148883225?q=translated%3Ano

(For these keys, the Spanish translation was equal to the English original.)

**Comment by caugner** [comment]
@jatempa I have just invited you as a translator for the Spanish Translation Team on Transifex.

Once the locale is "ready for use" (i.e. 100% translated), you can directly export the JSON file [via this link](https://www.transifex.com/vuejs/vue-cli/cli-ui/es/download/for_use/) and create a pull request here, so that @coderdiaz can release a new version of the npm package.

**Comment by coderdiaz** [comment]
@jatempa Can you help me with it?

**Comment by jatempa** [comment]
Of course ! beforehand my apologies for the late reply

**Comment by coderdiaz** [comment]
The new version `0.1.7` has been published. ✨

Thanks guys @jatempa @caugner 🎉
